saving to csv
AndVl1/Final-Count pull request #18
Opened 2020-05-18 09:51 UTC by AndVl1

2020-05-18 16:36 UTC, 102Rudy requested changes

2020-05-18 16:36 UTC, 102Rudy commented on app/src/main/java/com/techpark/finalcount/adding/views/activity/AddingActivity.kt
> +	private fun checkValues(): Boolean = mAddingBinding.name.text.isNotEmpty() &&
лучше более ясно назвать метод, что-нибудь типа isNameAndPriceFilled()

2020-05-18 16:36 UTC, 102Rudy commented on app/src/main/java/com/techpark/finalcount/auth/views/activity/AuthActivity.kt
> +		Utils.showMessage(applicationContext, "Login success!")
лучше использовать ресурсы для строк, а не хардкодить в коде

2020-05-18 16:36 UTC, 102Rudy commented on app/src/main/java/com/techpark/finalcount/data/dbexpimp/JSONParser.kt
> +		}
??

2020-05-18 16:36 UTC, 102Rudy commented on app/src/main/java/com/techpark/finalcount/data/dbexpimp/JSONParser.kt
> +		val result = ArrayList<String>()
в kotlin есть метод mutableListOf, listOf для создания списка, лучше использовать их

2020-05-18 16:36 UTC, 102Rudy commented on app/src/main/java/com/techpark/finalcount/data/dbexpimp/JSONParser.kt
> +	fun getCSVString(jsonArray: JSONArray): ArrayList<String> {
помнишь **D** в SOLID?
не возвращай конкретную реализацию здесь

2020-05-18 16:36 UTC, 102Rudy commented on app/src/main/java/com/techpark/finalcount/data/dbexpimp/JsonDbExportImportApiKt.kt
> +			Log.e(TAG, ex.toString())
isScope не нужно закрыть в блоке finally ? (я точно не помню)

2020-05-18 16:36 UTC, 102Rudy commented on app/src/main/java/com/techpark/finalcount/data/dbexpimp/JsonDbExportImportApiKt.kt
> +		return resultSet!!
если кинулось исключение в блоке try, то здесь упадет

2020-05-18 16:36 UTC, 102Rudy commented on app/src/main/java/com/techpark/finalcount/main/presenters/MainPresenter.kt
> +interface MainPresenter {
от BasePresenter не нужно наследоваться здесь?

2020-05-18 16:36 UTC, 102Rudy commented on app/src/main/java/com/techpark/finalcount/main/views/activity/MainActivity.kt
> +		return when (item.itemId) {
можно использовать `=` вместо `return`

2020-05-18 16:38 UTC, AndVl1 commented on app/src/main/java/com/techpark/finalcount/data/dbexpimp/JSONParser.kt
> +		}
забыл удалить, в итоге не потребовалось

2020-05-19 13:49 UTC, 102Rudy commented on app/src/main/java/com/techpark/finalcount/adding/views/activity/AddingActivity.kt
> +			} else Toast.makeText(applicationContext, R.string.adding_empty, Toast.LENGTH_SHORT).show()
```kotlin
} else {
    Toast.makeText(applicationContext, R.string.adding_empty, Toast.LENGTH_SHORT).show()
}
```

2020-05-19 13:49 UTC, 102Rudy commented on app/src/main/java/com/techpark/finalcount/auth/views/AuthView.kt
> +	fun showError(err: String  = "")
будет показываться просто что-то без описания?

2020-05-19 13:49 UTC, 102Rudy commented on app/src/main/java/com/techpark/finalcount/auth/views/activity/AuthActivity.kt
> +			mLoginActivityBinding.statusView.text = err
логика про выбирать getString(R.string.invalid) или err должна быть в presenter
а здесь тупо во вьюху нужно ставить то что придет, без проверок

2020-05-19 13:49 UTC, 102Rudy commented on app/src/main/java/com/techpark/finalcount/main/presenters/MainPresenterImpl.kt
> +				}.join()
насколько я помню, через async можно это разрулить, и будет сразу val path = mIOScope.async {}

2020-05-19 13:49 UTC, 102Rudy commented on app/src/main/java/com/techpark/finalcount/main/views/activity/MainActivity.kt
> +	)
а что будет если активити пересоздастся?

2020-05-20 21:53 UTC, merged