Authentification activity
AndVl1/Final-Count pull request #8
Opened 2020-03-24 12:38 UTC by AndVl1

[Auth to MVP](https://app.gitkraken.com/glo/board/5e6b66241332eb0011114dc6/card/5e788e9bf602dd001835602f)
[Authentification](https://app.gitkraken.com/glo/board/5e6b66241332eb0011114dc6/card/5e6b68d831df0b00124204c5)

2020-03-25 17:00 UTC, 102Rudy requested changes

2020-03-25 17:00 UTC, 102Rudy commented on app/src/main/java/com/techpark/finalcount/auth/model/User.kt
> +    val mAuth = FirebaseAuth.getInstance()
это лучше положить в конструктор

2020-03-25 17:00 UTC, 102Rudy commented on app/src/main/java/com/techpark/finalcount/auth/presenters/AuthPresenterImpl.kt
> +    private var authView: AuthView? = null
Определись: использовать префикс m или не использовать: пиши в одном стиле

2020-03-25 17:00 UTC, 102Rudy commented on app/src/main/java/com/techpark/finalcount/auth/presenters/AuthPresenterImpl.kt
> +        authView!!.setLoadingVisibility(true)
надо избегать force unwrap (`!!`)

2020-03-25 17:00 UTC, 102Rudy commented on app/src/main/java/com/techpark/finalcount/auth/presenters/AuthPresenterImpl.kt
> +            authView!!.showError("Invalid login or password")
надо избегать force unwrap (`!!`)

2020-03-25 17:00 UTC, 102Rudy commented on app/src/main/java/com/techpark/finalcount/auth/presenters/AuthPresenterImpl.kt
> +            authView!!.setLoadingVisibility(true)
надо избегать force unwrap (`!!`)

2020-03-25 17:00 UTC, 102Rudy commented on app/src/main/java/com/techpark/finalcount/auth/presenters/AuthPresenterImpl.kt
> +//        }
закомментированный код нужен?

2020-03-25 17:00 UTC, 102Rudy commented on app/src/main/java/com/techpark/finalcount/base/BaseActivity.kt
> +    override fun onCreate(savedInstanceState: Bundle?, persistentState: PersistableBundle?) {
какой смысл в этом переопределении этого метода?

2020-03-25 17:00 UTC, 102Rudy commented on app/src/main/java/com/techpark/finalcount/base/BasePresenter.kt
> +interface BasePresenter<v: BaseView> {
generic не по code style

2020-03-25 17:00 UTC, 102Rudy commented on app/src/main/java/com/techpark/finalcount/base/BaseView.kt
> +    fun getContext(): Context
а для чего этот метод у BaseView?
presenters ничего не должны знать про андроидовский контекст

2020-03-25 17:00 UTC, 102Rudy commented on app/src/main/java/com/techpark/finalcount/main/MainActivity.kt
> +            mAuth.currentUser!!.sendEmailVerification()
!!

2020-03-25 17:00 UTC, 102Rudy commented on app/src/main/java/com/techpark/finalcount/utils/Utils.kt
> +                       key: String?, data: Data): Intent {
а что за класс Data ?

2020-03-25 17:00 UTC, 102Rudy commented on app/src/main/java/com/techpark/finalcount/utils/Utils.kt
> +        fun setIntent(context: Context, destination: Class<*>?): Intent {
не совсем понимаю, для чего метод
вроде он создает интент, но и вроде сам запускает активити...

2020-03-25 17:00 UTC, 102Rudy commented on app/src/main/res/layout/activity_auth.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
можно использовать ConstraintLayout и полностью избежать вложенности

2020-03-25 17:00 UTC, 102Rudy commented on app/src/main/res/layout/activity_main.xml
> +        android:visibility="visible"
по умолчанию и так visible

2020-03-25 17:57 UTC, AndVl1 commented on app/src/main/java/com/techpark/finalcount/utils/Utils.kt
> +        fun setIntent(context: Context, destination: Class<*>?): Intent {
Взял его с примера MVP, в итоге с ним падало, сделал переключение просто из активити, а это забыл убрать, сейчас уберу

2020-03-25 18:05 UTC, AndVl1 commented on app/src/main/java/com/techpark/finalcount/auth/presenters/AuthPresenterImpl.kt
> +//        }
Дупликат кода из активити, по хорошему его в классе самой активити не должно быть, но я не знаю, как его сюда перенести, потому что метод startActivityForSignInWithProvider требует текущее активити в параметре

2020-03-25 20:59 UTC, AndVl1 commented
@102Rudy вроде бы всё исправил

2020-04-02 19:45 UTC, AndVl1 commented on app/src/main/java/com/techpark/finalcount/auth/views/activity/AuthActivity.kt
> +            mAuthPresenter.authGithub(this@AuthActivity)
Не уверен, насколько корректно так делать. Поправьте, если что не так

2020-04-05 08:42 UTC, 102Rudy commented on app/src/main/java/com/techpark/finalcount/auth/views/activity/AuthActivity.kt
> +            mAuthPresenter.authGithub(this@AuthActivity)
передавать контекст в презентер - плохая идея на самом деле
презентер по идеологии - платформонезависим

2020-05-16 07:49 UTC, 102Rudy requested changes

2020-05-16 07:49 UTC, 102Rudy commented on app/src/main/java/com/techpark/finalcount/auth/views/activity/AuthActivity.kt
> +    private val mCallbackManager: CallbackManager = CallbackManager.Factory.create() // facebook
вот этого в активити быть не должно, по хорошему
активити - это вьюха, в которой нет никакой логики. Она просто исполняет команды презентера и все

2020-05-16 07:49 UTC, 102Rudy commented on app/src/main/java/com/techpark/finalcount/base/BaseView.kt
> +interface BaseView {}
extra {}

2020-05-16 07:49 UTC, 102Rudy commented on app/src/main/java/com/techpark/finalcount/main/MainActivity.kt
> +    private val mAuth = FirebaseAuth.getInstance()
тоже не место в активити

2020-05-16 07:49 UTC, 102Rudy commented on app/src/main/java/com/techpark/finalcount/utils/Utils.kt
> +class Utils {
можно просто
```kotlin
object Utils {
    fun showMessage(context: Context?, message: String?) {
         Toast.makeText(context, message, Toast.LENGTH_SHORT).show()
    }
}
```

2020-05-16 07:49 UTC, 102Rudy commented on app/src/main/res/layout/activity_auth.xml
> +    <RelativeLayout
Relative внутри ConstraintLayout ?
Кажется layout неправильно сделан, оставь только ConstraintLayout

2020-05-16 07:59 UTC, closed without merging